# Generated by Django 3.0.7 on 2023-08-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Futbol', 'FUTBOL'), ('Ajedrez', 'AJEDREZ')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Iniciado', 'INICIADO'), ('Finalizado', 'FINALIZADO'), ('Suspendido', 'SUSPENDIDO'), ('Cancelado', 'CANCELADO')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'competencia',
            },
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Futbol', 'FUTBOL'), ('Ajedrez', 'AJEDREZ')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Iniciado', 'INICIADO'), ('Finalizado', 'FINALIZADO'), ('Suspendido', 'SUSPENDIDO'), ('Cancelado', 'CANCELADO')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'encuentro',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(default=1)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaFutbol',
            fields=[
                ('competencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competencia.Competencia')),
                ('titulares', models.IntegerField(default=1)),
                ('total_jugadores', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'competencia_futbol',
            },
            bases=('competencia.competencia',),
        ),
        migrations.CreateModel(
            name='EncuentroAjedrez',
            fields=[
                ('encuentro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competencia.Encuentro')),
            ],
            options={
                'db_table': 'encuentro_ajedrez',
            },
            bases=('competencia.encuentro',),
        ),
        migrations.CreateModel(
            name='EncuentroFutbol',
            fields=[
                ('encuentro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competencia.Encuentro')),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_equipo1', to='competencia.Equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_equipo2', to='competencia.Equipo')),
            ],
            options={
                'db_table': 'encuentro_futbol',
            },
            bases=('competencia.encuentro',),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competencia.Persona')),
                ('tipo', models.CharField(choices=[('Futbol', 'FUTBOL'), ('Ajedrez', 'AJEDREZ')], max_length=20, null=True)),
                ('numeroCamiseta', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'jugador',
            },
            bases=('competencia.persona',),
        ),
        migrations.CreateModel(
            name='TablaPocisionesFutbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=1)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencia_tabla_futbol', to='competencia.Competencia')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_tabla', to='competencia.Equipo')),
            ],
            options={
                'db_table': 'tabla_pocisiones',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Liga', 'LIGA'), ('Copa', 'COPA')], max_length=20, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencia_grupo', to='competencia.Competencia')),
                ('equipos', models.ManyToManyField(related_name='equipos_grupo', to='competencia.Equipo')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas_competencia', to='competencia.Temporada'),
        ),
        migrations.CreateModel(
            name='TablaPocisionesAjedrez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=1)),
                ('partidas_jugadas', models.IntegerField(default=1)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencia_tabla_ajedrez', to='competencia.Competencia')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_tabla', to='competencia.Jugador')),
            ],
            options={
                'db_table': 'tabla_pocisiones_ajedrez',
            },
        ),
        migrations.CreateModel(
            name='MarcadorFutbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo1', models.IntegerField(default=0)),
                ('equipo2', models.IntegerField(default=0)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentro_marcador', to='competencia.EncuentroFutbol')),
            ],
            options={
                'db_table': 'marcador',
            },
        ),
        migrations.CreateModel(
            name='MarcadorAjedrez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador1', models.IntegerField(default=0)),
                ('jugador2', models.IntegerField(default=0)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentro_marcador', to='competencia.EncuentroAjedrez')),
            ],
            options={
                'db_table': 'marcador_ajedrez',
            },
        ),
        migrations.CreateModel(
            name='Fichaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_fichados', to='competencia.Equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas_fichajes', to='competencia.Temporada')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_fichados', to='competencia.Jugador')),
            ],
            options={
                'db_table': 'fichaje',
            },
        ),
        migrations.AddField(
            model_name='encuentroajedrez',
            name='jugador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_jugador1', to='competencia.Jugador'),
        ),
        migrations.AddField(
            model_name='encuentroajedrez',
            name='jugador2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_jugador2', to='competencia.Jugador'),
        ),
        migrations.CreateModel(
            name='CompetenciaAjedrez',
            fields=[
                ('competencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competencia.Competencia')),
                ('numero_participantes', models.IntegerField(default=1)),
                ('jugadores', models.ManyToManyField(related_name='jugadores_competencia_ajedrez', to='competencia.Jugador')),
            ],
            options={
                'db_table': 'competencia_ajedrez',
            },
            bases=('competencia.competencia',),
        ),
    ]
