# Generated by Django 3.0.7 on 2023-08-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_encuentro_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuentro',
            old_name='resultado',
            new_name='ganador',
        ),
    ]
