# Generated by Django 3.0.7 on 2023-08-11 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0003_auto_20230809_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=65, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='N de documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=65, verbose_name='Nombres'),
        ),
    ]
