# Generated by Django 3.0.7 on 2023-08-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0004_auto_20230810_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuentro',
            name='ganador',
        ),
    ]
