# Generated by Django 3.0.7 on 2023-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0005_remove_encuentro_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcadorajedrez',
            name='puntos_jugador1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marcadorajedrez',
            name='puntos_jugador2',
            field=models.IntegerField(default=0),
        ),
    ]
