# Generated by Django 3.0.7 on 2023-08-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0006_auto_20230811_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcadorajedrez',
            name='jugador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador1_marcador_ajedrez', to='competencia.Jugador'),
        ),
        migrations.AlterField(
            model_name='marcadorajedrez',
            name='jugador2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador2_marcador_ajedrez', to='competencia.Jugador'),
        ),
    ]
