# Generated by Django 3.0.7 on 2023-08-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0009_auto_20230812_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
